package risk

import (
	"sync"
	"time"

	"github.com/Stratify-Systems/ThreatSIM/internal/core"
)

// riskScoreInternal is our internal representation that allows for O(1) deduplication
type riskScoreInternal struct {
SourceIP    string
Score       int
ThreatLevel core.ThreatLevel
FactorSet   map[string]struct{}
UpdatedAt   time.Time
}

// Engine calculates risk scores for entities (like Source IPs) based on
// alerts generated by the Detection Engine.
type Engine struct {
scores map[string]*riskScoreInternal
mu     sync.RWMutex

// Called when a risk score crosses into a new threat level or reaches critical
RiskUpdateSink func(core.RiskScore)
}

func NewEngine() *Engine {
return &Engine{
scores: make(map[string]*riskScoreInternal),
}
}

// ProcessAlert consumes an alert and adjusts risk scores accordingly.
func (e *Engine) ProcessAlert(alert core.Alert) {
e.mu.Lock()
defer e.mu.Unlock()

// Fallback to "global" if IP is missing somehow
ip := alert.SourceIP
if ip == "" {
ip = "global"
}

scoreState, exists := e.scores[ip]
if !exists {
scoreState = &riskScoreInternal{
SourceIP:    ip,
Score:       0,
ThreatLevel: core.ThreatLow,
FactorSet:   make(map[string]struct{}),
}
e.scores[ip] = scoreState
}

// Base logic - each rule defines its base risk score. 
inc := 10
switch alert.Severity {
case core.SeverityCritical:
inc = 90
case core.SeverityHigh:
inc = 60
case core.SeverityMedium:
inc = 30
case core.SeverityLow:
inc = 10
}

scoreState.Score += inc

// Cap at 100
if scoreState.Score > 100 {
scoreState.Score = 100
}

// Update Threat Level
switch {
case scoreState.Score >= 81:
scoreState.ThreatLevel = core.ThreatCritical
case scoreState.Score >= 61:
scoreState.ThreatLevel = core.ThreatHigh
case scoreState.Score >= 31:
scoreState.ThreatLevel = core.ThreatMedium
default:
scoreState.ThreatLevel = core.ThreatLow
}

if alert.RuleName != "" {
scoreState.FactorSet[alert.RuleName] = struct{}{}
}
scoreState.UpdatedAt = time.Now()

if e.RiskUpdateSink != nil {
// Convert to external core.RiskScore and slice factors
sc := core.RiskScore{
SourceIP:    scoreState.SourceIP,
Score:       scoreState.Score,
ThreatLevel: scoreState.ThreatLevel,
UpdatedAt:   scoreState.UpdatedAt,
Factors:     make([]string, 0, len(scoreState.FactorSet)),
}

for k := range scoreState.FactorSet {
sc.Factors = append(sc.Factors, k)
}

// Emit the current state
e.RiskUpdateSink(sc)
}
}

func (e *Engine) GetScore(ip string) core.RiskScore {
e.mu.RLock()
defer e.mu.RUnlock()

if state, ok := e.scores[ip]; ok {
sc := core.RiskScore{
SourceIP:    state.SourceIP,
Score:       state.Score,
ThreatLevel: state.ThreatLevel,
UpdatedAt:   state.UpdatedAt,
Factors:     make([]string, 0, len(state.FactorSet)),
}
for k := range state.FactorSet {
sc.Factors = append(sc.Factors, k)
}
return sc
}
return core.RiskScore{
SourceIP:    ip,
ThreatLevel: core.ThreatLow,
}
}
