package risk

import (
	"sync"
	"time"

	"github.com/Stratify-Systems/ThreatSIM/internal/core"
)

// Engine calculates risk scores for entities (like Source IPs) based on
// alerts generated by the Detection Engine.
type Engine struct {
	scores map[string]*core.RiskScore
	mu     sync.RWMutex

	// Called when a risk score crosses into a new threat level or reaches critical
	RiskUpdateSink func(core.RiskScore)
}

func NewEngine() *Engine {
	return &Engine{
		scores: make(map[string]*core.RiskScore),
	}
}

// ProcessAlert consumes an alert and adjusts risk scores accordingly.
func (e *Engine) ProcessAlert(alert core.Alert) {
	e.mu.Lock()
	defer e.mu.Unlock()

	// Fallback to "global" if IP is missing somehow
	ip := alert.SourceIP
	if ip == "" {
		ip = "global"
	}

	score, exists := e.scores[ip]
	if !exists {
		score = &core.RiskScore{
			SourceIP:    ip,
			Score:       0,
			ThreatLevel: core.ThreatLow,
		}
		e.scores[ip] = score
	}

	// Base logic - each rule defines its base risk score. 
	// We'll need that populated in the alert, but for now we can infer from Severity
	// if RiskScore isn't in alert. Wait, alert doesn't have RiskScore. Let's add simple baseline.
	inc := 10
	switch alert.Severity {
	case core.SeverityCritical:
		inc = 90
	case core.SeverityHigh:
		inc = 60
	case core.SeverityMedium:
		inc = 30
	case core.SeverityLow:
		inc = 10
	}

	score.Score += inc

	// Cap at 100
	if score.Score > 100 {
		score.Score = 100
	}

	// Update Threat Level
	switch {
	case score.Score >= 81:
		score.ThreatLevel = core.ThreatCritical
	case score.Score >= 61:
		score.ThreatLevel = core.ThreatHigh
	case score.Score >= 31:
		score.ThreatLevel = core.ThreatMedium
	default:
		score.ThreatLevel = core.ThreatLow
	}

	score.Factors = append(score.Factors, alert.RuleName)
	score.UpdatedAt = time.Now()

	if e.RiskUpdateSink != nil {
		// Send a copy to avoid race conditions
		sc := *score
		
		// If we want to only send on level up, we'd track previous level.
		// For now, always emit.
		e.RiskUpdateSink(sc)
	}
}

func (e *Engine) GetScore(ip string) core.RiskScore {
	e.mu.RLock()
	defer e.mu.RUnlock()

	if s, ok := e.scores[ip]; ok {
		return *s
	}
	return core.RiskScore{
		SourceIP:    ip,
		ThreatLevel: core.ThreatLow,
	}
}
